spring.application.name=AppControlGastos

server.port=8080
spring.datasource.url=jdbc:h2:mem:AppControlGastos
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.h2.console.enabled=true
spring.h2.console.path=/h2
spring.jpa.hibernate.ddl-auto=none
logging.level.org.springframework=debug


spring.sql.init.mode=ALWAYS
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

server.servlet.context-path=/app-control-gastos

